# define   a neural network like this :

--NeuralNetwork(<br /> 
  (flatten): Flatten(start_dim=1, end_dim=-1)<br /> 
  (linear_relu_stack): Sequential(<br /> 
    (0): Linear(in_features=784, out_features=512, bias=True)<br /> 
    (1): ReLU()<br /> 
    (2): Linear(in_features=512, out_features=512, bias=True)<br /> 
    (3): ReLU()<br /> 
    (4): Linear(in_features=512, out_features=10, bias=True)<br /> 
  )<br /> 
)<br /> 

In [10]:
import torch
from torch import nn

class NeuralNetwork(nn.Module) :
    def __init__(self):
        super(NeuralNetwork , self).__init__() 
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
        nn.Linear(28*28,512),
        nn.ReLU(),
        nn.Linear(512,512),
        nn.ReLU(),
        nn.Linear(512,10)
        
    )
    
    def forward(self,x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits
model = NeuralNetwork().to("cpu")
print(model)


NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [15]:
ImageData = torch.rand((1,28,28),device="cpu")

In [18]:
logits= model(ImageData)
logits

tensor([[-0.0302,  0.0672, -0.0091,  0.0550,  0.0405, -0.0759, -0.1165,  0.1298,
          0.0066, -0.0633]], grad_fn=<AddmmBackward0>)

In [21]:
pred_prob = nn.Softmax(dim=1)(logits)
pred_prob

tensor([[0.0967, 0.1066, 0.0988, 0.1053, 0.1038, 0.0924, 0.0887, 0.1135, 0.1004,
         0.0936]], grad_fn=<SoftmaxBackward0>)

In [24]:
y = pred_prob.argmax(1)
y

tensor([7])

In [26]:
print(f"Predicted class: {y}")

Predicted class: tensor([7])


In [28]:
input_image = torch.randn(3,28,28)

In [29]:
input_image.shape

torch.Size([3, 28, 28])